name: ffbuild

on:
  push:
    branches:
      - 'dev-dev'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v4

            - name: build
              run: ./build.sh

            - name: upload
              uses: actions/upload-artifact@v4
              with:
                  name: packages
                  path: ./prefix.tar