name: ffbuild

on:
  push:
    branches:
      - 'dev-glibc'

jobs:
    build:
        runs-on: ubuntu-24.04
        steps:
            - name: checkout
              uses: actions/checkout@v4

            - name: build
              run: ./build.sh

            - name: upload
              uses: actions/upload-artifact@v4
              with:
                  name: glibc
                  path: ./glibc-*.tar